Список контактов и детали контакта. Только верстка и навигация
sancshous/AndroidProject pull request #2
Opened 2020-04-28 11:26 UTC by sancshous

1. В основном активити находится только контейнер FrameLayout для 2 фрагментов
2. Также созданы land-layout'ы для фрагментов
3. Кнопка "Назад" работает
4. Заголовок в Toolbar меняется на "Список контактов" и "Детали контакта"
5. colorPrimary = #a2642d
    colorPrimaryDark = #a2642d
    colorAccent = #f91f05
![Скриншот 28-04-2020 131950](https://user-images.githubusercontent.com/51170640/80481922-64da8980-8964-11ea-94a4-533acb515f24.png)
![Скриншот 28-04-2020 132010](https://user-images.githubusercontent.com/51170640/80481924-65732000-8964-11ea-983a-8658c5d30067.png)
![Скриншот 28-04-2020 152026](https://user-images.githubusercontent.com/51170640/80481925-660bb680-8964-11ea-9d77-d025c25d7782.png)
![Скриншот 28-04-2020 152042](https://user-images.githubusercontent.com/51170640/80481926-660bb680-8964-11ea-8fba-3f9eb2a9cf15.png)

2020-04-28 11:46 UTC, goblinr requested changes

2020-04-28 11:46 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +                FragmentManager fragmentManager = getActivity().getSupportFragmentManager();
По условию ДЗ, фрагменту нужно передать ID выбранного контакта в аргументах

2020-04-28 11:46 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MainActivity.java
> +        ftrans.add(R.id.fragment_container, frag1).commit();
Здесь возможна ситуация добавления нескольких фрагментов, например, после поворота экрана - `onCreate` вызовется снова и фрагмент добавится 2-ой раз. Необходимо проверить `savedInstanceState` перед добавлением фрагмента

2020-04-28 11:46 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MainActivity.java
> +    FragmentDetails frag2;
Хранить ссылки на фрагменты - это прямой путь к утечкам памяти выделенных под них. Т.к. жизненные циклы активности и фрагметов не совпадают.
Почитай про сборщик мусора в Java и про жесткие ссылки.

2020-04-28 11:46 UTC, goblinr commented on AndroidProject/app/src/main/res/layout-land/fragment_details.xml
> +    <LinearLayout
Вкладывать любой контейнер в ConstraintLayout - затратно и бессмысленно. ConstraintLayout имеет все инструменты для того чтобы избавиться от вложенности

2020-04-28 11:46 UTC, goblinr commented on AndroidProject/app/src/main/res/layout-land/fragment_details.xml
> +                android:id="@+id/imageView4"
Такие названия - не читаемы и не понятно что за ними стоит. Нужно давать более осмысленные названия

2020-04-28 11:46 UTC, goblinr commented on AndroidProject/app/src/main/res/layout-land/fragment_details.xml
> +                android:id="@+id/imageView4"
Это касается всего проекта

2020-04-28 11:46 UTC, goblinr commented on AndroidProject/app/src/main/res/layout-land/fragment_details.xml
> +                android:layout_marginTop="13dp"
Нечетные размеры.
Нужно от них избавляться

2020-04-28 11:46 UTC, goblinr commented on AndroidProject/app/src/main/res/layout-land/fragment_details.xml
> +                android:layout_marginTop="13dp"
Это касается всего проекта

2020-04-28 11:46 UTC, goblinr commented on AndroidProject/app/src/main/res/layout/fragment_details.xml
> +                android:layout_height="150dp"
Не имеет смысла заводить целый отдельный лэйаут для  landscape ориентации, если структура не меняется, а меняются только размеры. В этом случае, достаточно просто пере-определить ресурсы размеров, нежели дублировать огромный кусок верстки

2020-04-28 13:02 UTC, sancshous commented on AndroidProject/app/src/main/java/com/example/androidproject/MainActivity.java
> +        ftrans.add(R.id.fragment_container, frag1).commit();
Как загружать теперь? Создавать новый комит?

2020-04-28 14:47 UTC, sancshous commented on AndroidProject/app/src/main/res/layout/fragment_details.xml
> +                android:layout_height="150dp"
Я попробовал так в MainActivity.java, но у меня крашит при повороте` if (getResources().getConfiguration().orientation == Configuration.ORIENTATION_LANDSCAPE) {
            TextView ContactName = (TextView) findViewById(R.id.ContactName);
            LinearLayout.LayoutParams params = (LinearLayout.LayoutParams) ContactName.getLayoutParams();
            params.width = 100;
            ContactName.setLayoutParams(params);
        }`

2020-04-28 15:24 UTC, goblinr requested changes

2020-04-28 15:24 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +                FragmentDetails frag2 = new FragmentDetails(R.id.ContactID);
Так делать нельзя. У фрагмента при пересоздании - будет вызван конструктор без параметров, поэтому то что ты сейчас сделал - приведет к крэшу приложения, т.к. конструктора без параметров у фрагмента нет.

Нужно передавать id через аргументы. Посмотри слайды лекции еще раз, про передачу параметров фрагменту.

2020-04-28 15:24 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MainActivity.java
> +            params.width = 100;
Нет. Так делать точно не стоит. Если ты хочешь заоверайдить размеры для landscape ориентации делай это так:
у тебя есть **res/values**
добавь **res/values-land**
и туда и туда добавь файл **dimens.xml**
В одном у тебя будет:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
     <dimen name="my_margin">16dp</dimen>
</resources>
```
в другом, например:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
     <dimen name="my_margin">8dp</dimen>
</resources>
```
Ну и в верстке используй этот размер:
```xml
    <TextView  android:layout_margin="@dimen/my_margin" />
```

2020-04-28 15:24 UTC, goblinr commented on AndroidProject/app/src/main/res/layout/fragment_details.xml
> +        android:layout_height="114dp"
Жесткие размеры не поворотливы. Старайся использовать `wrap_content` либо `0dp` с привязками как минимум для 3-х сторон вьюшки.
Это касается всей верстки

2020-04-28 15:25 UTC, goblinr commented on AndroidProject/app/src/main/res/layout/fragment_details.xml
> +                android:layout_height="150dp"
Отписался ниже, как нужно делать.
Крэш у тебя не из-за этого, а из-за того что ты конструктор с параметром в фрагменте добавил

2020-04-28 15:28 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MainActivity.java
> +        ftrans.add(R.id.fragment_container, frag1).commit();
Да все изменения - новыми комитами добавляются.

2020-04-28 15:29 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MainActivity.java
> +        ftrans.add(R.id.fragment_container, frag1).commit();
Не совсем понял, о чем спрашивается. Про коммит транзакции фрагмента или про то как исправления в PR заливать?

2020-04-29 16:13 UTC, goblinr approved these changes

2020-04-29 16:20 UTC, merged