Bind service
sancshous/AndroidProject pull request #3
Opened 2020-05-06 09:42 UTC by sancshous

2020-05-06 10:49 UTC, goblinr requested changes

2020-05-06 10:49 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentDetails.java
> +        details = getArguments().getStringArray("DETAILS");
По ТЗ к домашнему заданию, детали контакта нужно получать из сервиса по ID асинхронно.

2020-05-06 10:49 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +            persons = getArguments().getParcelableArrayList("Parcel");
По ТЗ нужно получать список контактов из сервиса асинхронно.

2020-05-06 10:49 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +    private TextView contactPhone;
ссылки на View необходимо обнулять в `onDestroyView` чтобы не было утечек памяти

2020-05-06 10:49 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/Person.java
> +    private String description;
`final` ко всем полям

2020-05-06 10:49 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MainActivity.java
> +                mService.getPerson(bridge); //забираем данные из сервиса
Видимо, ты неверно понял ДЗ. Данные должны загружать сами фрагменты через сервис, а не активность

2020-05-06 10:49 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/SimpleService.java
> +    public void getPerson(final Bridge bridge){
По ДЗ у сервиса должно быть 2 метода

2020-05-06 10:49 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/SimpleService.java
> +                    bridge.getData(person);
Здесь кроется ошибка. В твоем методе обратного вызова у `Bridge.getData` на данный момент происходит запуск транзакции фрагмента. Т.к. ты вызываешь этот метод на отдельном потоке - это приведет к ошибке, т.к. транзакцию фрагментов можно запускать только с главного потока программы

2020-05-08 03:32 UTC, goblinr requested changes

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentDetails.java
> +        getActivity().bindService(intent, serviceConnection, Context.BIND_AUTO_CREATE);
`requireActivity()`

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentDetails.java
> +            getActivity().unbindService(serviceConnection);
1. `requireActivity()`
2. если `bindService()` происходит в `onStart()`, то и `unbindService()` нужно делать в `onStop()` а не в `onDestroy()`

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentDetails.java
> +    private Observer observer = new Observer() {
все поля класса должны быть определены в начале класса

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentDetails.java
> +    SimpleService mService;
`private`

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentDetails.java
> +        }
Этот метод не нужен для `FragmentDetails`, следовательно, имеет смысл интерфейс `Observer` разбить на 2 интерфейса - в одном будет `updateShort(List<Person> list)`, а в другом - `updateFull(Person person)`

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +                        .addToBackStack(null).commit();
Здесь может быть крэш приложения. Если `personList` к этому моменту еще не загружен.

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +        getActivity().bindService(intent, serviceConnection, Context.BIND_AUTO_CREATE);
`requireActivity()`

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +            getActivity().unbindService(serviceConnection);
см. комментарии выше

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +    }
См. комментарий про ненужность методов и разделение интерфейса Observer

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MainActivity.java
> +    };
Зачем этот `ServiceConnection` здесь? Ты уже подцепляешься к сервису в фрагментах.

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MainActivity.java
> +        isBound = true;
Это все уже не нужно, т.к. фрагменты у тебя сами подцепляются к сервису

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MainActivity.java
>          }
Это все уже не нужно, т.к. фрагменты у тебя сами подцепляются к сервису

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/Observable.java
> +    void notifyObserverPerson(int id);
См. комментарий про разделение интерфейса на 2

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/Observer.java
> +}
Нужно разделить на 2 интерфейса

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/Repository.java
> +public class Repository { //типо хранилище контактов
Если пишешь комментарии - то делай это по правилам JavaDoc. https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/SimpleService.java
> +public class SimpleService extends Service implements Observable{
Переименуй сервис в адекватное название.

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/SimpleService.java
> +    private List<Observer> observers = new ArrayList<>();
Чтобы самостоятельно не следить за отпиской в клиентах - воспользуйся слабыми ссылками:
```java
private List<WeakReference<Observer>> observers = new ArrayList<>();
```

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/SimpleService.java
> +        return foo.get();
Ничего не поменялось. Ты по-прежнему блокируешь вызывающий поток

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/SimpleService.java
> +        return foo.get().get(id);
Здесь тоже самое

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/SimpleService.java
> +        ExecutorService executor = Executors.newSingleThreadExecutor();
Не нужно каждый раз заново создавать `ExecutorService` - сделай это 1 раз при инициализации класса

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/SimpleService.java
> +        ExecutorService executor = Executors.newSingleThreadExecutor();
Не нужно каждый раз заново создавать ExecutorService - сделай это 1 раз при инициализации класса

2020-05-08 03:32 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/SimpleService.java
> +    }
Как я уже написал выше - воспользуйся слабыми ссылками, что бы не следить вызывать `delete` в клиентах

2020-05-09 13:52 UTC, goblinr requested changes

2020-05-09 13:52 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentDetails.java
> +        getActivity().bindService(intent, serviceConnection, Context.BIND_AUTO_CREATE);
Не исправлено

2020-05-09 13:52 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentDetails.java
> +            getActivity().unbindService(serviceConnection);
1-й пункт не исправлен

2020-05-09 13:52 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentDetails.java
> +            detalDescription.setText(person.getDescription());
Прежде чем трогать вьюшки, следует проверить, что они еще не `null`, т.к. `updateFull` может вызваться уже после `onDestroyView` фрагмента

2020-05-09 13:52 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +            contactPhone.setText(String.valueOf(list.get(0).getPhone()));
Проверять ссылки на `null`

2020-05-09 13:52 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +                        .addToBackStack(null).commit();
Не исправлено

2020-05-09 13:52 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +        getActivity().bindService(intent, serviceConnection, Context.BIND_AUTO_CREATE);
Не исправлено

2020-05-09 13:52 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +    private List<ObserverDetails> observersDetails = new ArrayList<>();
Что это? Зачем тебе слабые ссылки на списки наблюдателей и одновременно жесткие ссылки на списки наблюдателей? Когда я говорил про слабые ссылки, я имел в виду сделать так:
```java
private List<WeakReference<ObserverList>> observerList = new ArrayList<>();
```

2020-05-09 13:52 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +        return foo.get();
Вызов метода `get()` на `Future` всегда приводит к блокированию потока, на котором это происходит, я уже это в 3-й раз пишу. Не используй `get()`!

2020-05-09 13:52 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +        return foo.get().get(id);
то же самое

2020-05-09 13:52 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +        observerListWeak.get().add(o);
Это полный бред! Почитай про то как правильно работать со слабыми ссылками. И про то как GC работает!!

2020-05-09 13:52 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +        observerDetailsWeak.get().add(o);
тоже самое

2020-05-09 13:52 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +                observerListWeak.get().get(i).updateShort(getPersonsList());
2 ошибки в одной строчке кода:
неверная работа со слабыми ссылками и блокирование главного потока программы

2020-05-09 13:52 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +                observerDetailsWeak.get().get(i).updateFull(getFullInfo(id));
тоже самое

2020-05-09 13:53 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/SimpleService.java
> +    private List<Observer> observers = new ArrayList<>();
Не исправлено

2020-05-09 13:54 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/SimpleService.java
> +        return foo.get();
Не исправлено

2020-05-09 13:54 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/SimpleService.java
> +        return foo.get().get(id);
Не исправлено

2020-05-10 11:33 UTC, sancshous commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +        getActivity().bindService(intent, serviceConnection, Context.BIND_AUTO_CREATE);
что это значит requireActivity()? Заменить getActivity() на requireActivity()?

2020-05-10 11:35 UTC, sancshous commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +        return foo.get();
А что использовать?

2020-05-10 12:34 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +        getActivity().bindService(intent, serviceConnection, Context.BIND_AUTO_CREATE);
Да, заменить

2020-05-10 12:36 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +        return foo.get();
Используй `Runnable` вместо  `Callable`. 
Я в последней лекции показал как можно сделать асинхронное взаимодействие, пересмотри.

2020-05-10 15:56 UTC, goblinr requested changes

2020-05-10 15:56 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentDetails.java
> +                detalDescription.setText(person.getDescription());
Изменять контент вьюшек можно только на главном потоке программы. У тебя метод `updateFull` в сервисе вызывается не на главном потоке. 
Тебе нужно добавить в EventLooper главного потока отложенную работу, в которой уже менять контент вьюшек. Сделать это можно либо в сервисе, либо здесь в фрагменте

2020-05-10 15:56 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +                contactPhone.setText(String.valueOf(list.get(0).getPhone()));
Тоже самое и здесь

2020-05-10 15:56 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +        executor.shutdown();
Ты делаешь submit и тут же shutdown - это не верно

2020-05-10 15:56 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +        executor.shutdown();
Здесь тоже самое

2020-05-10 15:58 UTC, goblinr requested changes

2020-05-10 15:58 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +                callback.updateShort(repository.getPersons());
Утечка памяти. `callback` нужно сохранить в слабую ссылку

2020-05-10 15:58 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +                callback.updateFull(repository.getPersons().get(id));
Утечка памяти. `callback` нужно сохранить в слабую ссылку

2020-05-11 03:27 UTC, goblinr requested changes

2020-05-11 03:27 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentDetails.java
> +                    if((person.getName() != null) || (person.getPhone() != 0) || (person.getEmail() != null) || (person.getDescription() != null)) {
на `null` следует проверять вьюшки а не данные. Т.к. View у фрагмента к этому моменту может быть уничтожена, т.е. `onDestroyView()` может быть вызван к этому моменту.

2020-05-11 03:27 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +                    if ((list.get(0).getName() != null) || (list.get(0).getPhone() != 0)) {
Проверять на  `null` вьюшки

2020-05-11 03:27 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +                weakCallbackList.get().updateShort(repository.getPersons());
Неверная работа со слабой ссылкой. Почитай про сборщик мусора в Java  и типы ссылок, как они работают. 
Здесь у тебя может произойти `NullPointerException`, т.к. ты:
1. не присваиваешь результат метода `get()` у `WeakReference` в жесткую ссылку
2. не проверяешь этот результат на `null`

2020-05-11 03:27 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/MyService.java
> +                weakCallbakInfo.get().updateFull(repository.getPersons().get(id));
неверная работа со слабой ссылкой

2020-05-11 13:08 UTC, goblinr requested changes

2020-05-11 13:08 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentDetails.java
> +                    if((detalName != null) || (detalPhone != null) || (detalMail != null) || (detalDescription != null)) {
Если ты выносишь проверку вьюшек в один оператор `if` - то нужно объединять условия через `&&`

2020-05-11 13:08 UTC, goblinr commented on AndroidProject/app/src/main/java/com/example/androidproject/FragmentList.java
> +                    if ((contactName != null) || (contactPhone != null)) {
`&&`

2020-05-11 15:01 UTC, goblinr approved these changes

2020-05-11 15:12 UTC, merged